module.exports = {
  plugins: ['react', 'react-native', 'react-native-globals', '@typescript-eslint'],
  extends: [
    './rules/best-practices',
    './rules/errors',
    './rules/es6',
    './rules/imports',
    './rules/node',
    './rules/react',
    './rules/strict',
    './rules/style',
    './rules/variables',
  ].map(require.resolve),
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
    },
  },
  rules: {
    'react-native/sort-styles': 'off',
    'newline-per-chained-call': 'off',
    'react-native/no-raw-text': 'error',
    'react-native/no-color-literals': 'error',
    'react-native/no-inline-styles': 'warn',
    'react-native/no-unused-styles': 'warn',
  },
  env: {es6: true},
  globals: {
    __static: false,
    webview: false,
    localStorage: false,
    IntervalID: false,
    TimeoutID: false,
    Class: false,
    FileReader: false,
    Event: false,
    HTMLInputElement: false,
    FormData: false,
    HTMLTextAreaElement: false,
    Element: false,
    File: false,
    fetch: false,
    __DEV__: false,
    btoa: false,
    alert: false,
    window: false,
    document: false,
  },
};
